### ISSUE TITLE
Mouse control

### ISSUE THREAD

**Issue by MarcLeclere** [LucasBorboleta/pijersi-certu#1]
It would be great if game could be played using mouse controls.
Maybe repository owner could give me permissions to contribute by creating a new branch !

**Comment by LucasBorboleta** [comment]
Oh ! Yes, it would be great. And I am ready to accept such contribution.

Regarding the new branch creation, I am confused ; the GitHub documentation says "You can always create a branch in GitHub Desktop if you have read access to a repository, but you can only push the branch to GitHub if you have write access to the repository". So it seems that once the repo is cloned you should be able to create a new branch. Am I wrong ?

**Comment by LucasBorboleta** [comment]
I did it. Could you confirm that you no longer blocked ?

**Comment by MarcLeclere** [comment]
It works!

**Comment by LucasBorboleta** [comment]
Cool ! 
However, I am wondering if it is the canonical way. I have already contributed to another project without the need (my perception at least) to ask for being a "collaborator". The workflow has been : 
1. fork the origin repo "R" to my list of own repos "F" ; 
2. clone the forked repo "F" to my computer disk "Fd";
3. create a branch "B" on "Fd";
4. create commits on "B" on "Fd" and push them on "F";
5. when ready talk to owner of "R" and create a pull request from "F".

So question : did you "fork" my repo and have been blocked ? or did you "clone" my repo and have been blocked ?

**Comment by MarcLeclere** [comment]
I think you are right. I didn't follow the correct way : I cloned directly your repo on my computer and were blocked at the push step. I should have do a fork, I think it would have worked.

**Comment by LucasBorboleta** [comment]
OK. Let us go on this way. We could change that later, maybe.

**Comment by MarcLeclere** [comment]
Hi,
Prototype on my branch is quite playable. I invite you to test it !

**Comment by LucasBorboleta** [comment]
Hi Marc, 
Excellent ! You did it fast.
As soon as I am done with my tasks on the first local Pijersi tournament, I will enjoy to test your branch.

**Comment by LucasBorboleta** [comment]
Hi Marc !
Right now, I just made a first test, after installing your branch. My immediat feedback :
- It works ! 
- It is helpful for exploring the possible moves. It will help both beginners and confirmed players.
- I saw the synchronization with the input widget ; nice !
- I discovered how to UNDO the first action : just click again in the source hexagaon.
- But how to UNDO the second action, after the selection of the first action. Is it possible ?
- The chosen colors and their opacity levels might be discussed ...
- I haven't yet watch your implementation, but I have been surprised to discover matplotlib.
Beside details to be discussed, you did a very good job !!! After a few tunings and some explanation, I can see that merged in a short term. Surely, live discussion in another channel would help such finalization ...

**Comment by MarcLeclere** [comment]
Some elements before we met IRL:

- About syncrhonization with input widget: I need to add some protection if user modifies direclty the input values during GUI input process
- Actually, to UNDO a move, you can click everywhere else in the drawing
- You can't UNDO a second action, as I propose a "1-click" input process. Maybe we could add a "back" button to cancel an user input.
- Of course, we can change colors! Only thing I wanted is to make clear when a stack is selected or not (only the upper cube)
- I use matplotlib just to get the fonction contains_point. with a simple command, I can directly know if a hexagon contains a given point !

**Comment by LucasBorboleta** [comment]
Hi Marc !

Thanks for your explanations.
I tested the gesture for UNDO, either one-action or two-actions moves. It is OK.
I agree that some geometric adjusment has to be done on the board picture (a bit of mismatch with higlighted hexagons).

Here is my proposal for going on:
- You finish stuff you told me about "Resume".
- I merge your branch.
- I add a CONTRIBUTORS.md file with MarcLeclere cited (give me an email if you want).
- I freeze the repo with a tag "1.1.0.rc1"
- I search for new colors, based on wood harmony (with the help of Adobe color wheel).
- I fix the litttle hexagon mismatch.
- I test my idea for a simple function "point is inside pijersi regular hexagon" to get rid of matplotlib.
- I review more carefully the code.
- You test my choices, we converge.
- I freeze a version 1.1.0

No pressure regarding the timeline !
Would you agree ?

**Comment by MarcLeclere** [comment]
Hi,

Before freezing the repo, I will try to:
- Fix the process flow for the "resume" case
- Add action input protections
- Add checkbox for easy mode
Once I do that, I agree to continue as you say. I propose marccellere@gmail.com for public mail in CONTRIBUTORS.md

**Comment by LucasBorboleta** [comment]
Hi Marc,
So it is agreed !
Again, no pressure regarding the timeline.

**Comment by MarcLeclere** [comment]
Hi!
I just pushed my last commit. It contains changes as I described in my last post. I also improved a little highlight logics.
I think you can now take the time to try !

**Comment by LucasBorboleta** [comment]
Hi,
Fine !

**Comment by LucasBorboleta** [comment]
Hi,
Today, I am in the process of merging your branch.

**Comment by MarcLeclere** [comment]
Ok, great !

**Comment by LucasBorboleta** [comment]
Hi Marc,

The version v1.1.0-rc1 is now released, after the merge of your branch.

The minor changes I made are : updating of the version string ; reducing the size of the canvas being found too large, at least for my own laptop screen (could it be dynamically resized in some future version ?) And, of course, you are quoted as a contributor in the release notice and in the CONTRIBUTORS.md. Tell me if something is wrong regarding information about this release.

**Comment by MarcLeclere** [comment]
Ok, nice !

**Comment by LucasBorboleta** [comment]
Hi Marc !
I am in the process of reviewing your code, and hopefully also to fix the "take pictures" feature.

**Comment by MarcLeclere** [comment]
OK great !
Next tume we meet, I would like to discuss about the spinning widget "turn".

Le lun. 26 sept. 2022, 20:43, Lucas Borboleta ***@***.***> a
écrit :

**Comment by LucasBorboleta** [comment]
This week I have reviewed your code on mouse control. It is understood, now. Also, I have performed some cleaning. Now, I am in the process of implementing other features we have discussed. In the mid-time, the IA engine has been boosted (X2 on Minimax2 and Minimax3).

**Comment by MarcLeclere** [comment]
Ok great ! I tried to make some git diff, and all is red&green ! Hope that it doesn't mean it took to much of your time to make the review and the cleaning.
